### ISSUE TITLE
Kodi 19.4

### ISSUE THREAD

**Issue by Arthur1967** [linaspurinis/mdblist.com#1]
Which Kodi add-ons have this option I know the umbrella does thank you

**Comment by linaspurinis** [comment]
Umbrella and TheMovieDB Helper support MDBList.

Umbrella:
https://github.com/umbrellaplug/umbrellaplug.github.io 
TheMovieDB:
https://github.com/jurialmunkey/plugin.video.themoviedb.helper 

Also, you can use Trakt.tv lists with other plugins, MDBList allows syncing your lists to Trakt.tv.

**Comment by Arthur1967** [comment]
Those are the two I have and I will definitely let you know I would contact other developers because I think this is a great little feature if you come up with other things let me know I'm following you on here thank you and have a good day
