### ISSUE TITLE
A Rotten Tomatoes list is not updated

### ISSUE THREAD

**Issue by franciscobeltran** [linaspurinis/mdblist.com#13]
Hi, I tried to add this list from Rotten Tomatoes ([25 Most Popular TV Shows Right Now: What to Watch on Streaming](https://editorial.rottentomatoes.com/guide/popular-tv-shows/)) as an external list but it fails to update.

Does anyone know why or could fix it? Thanks in advance!

**Comment by linaspurinis** [comment]
Thanx, should be fixed now.
