### ISSUE TITLE
Advanced search not populating

### ISSUE THREAD

**Issue by Arthur1967** [linaspurinis/mdblist.com#16]
https://www.imdb.com/search/title/?title_type=tv_miniseries,tv_episode,tv_series&genres=!short&release_date=2024-01-01,2024-12-31&countries=US&languages=en

**Comment by linaspurinis** [comment]
Hi, thanx for report, looks like sha256Hash changed for IMDb search, I updated it and now it should refresh on next update.

**Comment by Arthur1967** [comment]
Thank you that's why I subscribed to you because you fix the issue fast. Have a good day.
