### ISSUE TITLE
Static Lists not synced with Trakt

### ISSUE THREAD

**Issue by Cheezzhead** [linaspurinis/mdblist.com#18]
I'm unable to remove items from a static list. I don't see any option for it in the web interface (unless I'm blind), and removing them from the connect trakt list does nothing.

How do I remove stuff from my lists?

**Comment by linaspurinis** [comment]
I agree it's not very obvious but you must click on the static list icon to remove or add
![CleanShot 2024-09-08 at 17 26 35@2x](https://github.com/user-attachments/assets/247a51b4-b88a-49a1-8ca1-f104737a3212)

**Comment by Cheezzhead** [comment]
Oof, I did see that button but didn't expect there to be a submenu. Thanks!
