### ISSUE TITLE
How to use Joined Lists

### ISSUE THREAD

**Issue by Cheezzhead** [linaspurinis/mdblist.com#19]
I have a dynamic list that contains Star Wars movies and tv shows, in a joined list:

![mdblist - star wars](https://github.com/user-attachments/assets/72f4de21-b8e6-4e4e-ba17-61f4a2e032b8)

There is, however, only one link to reach this list, and I can't find any way to specify whether I want to see the movies or TV shows. [The link itself](https://mdblist.com/lists/cheezzhead/evergreen-franchises-star-wars) only shows 11 items, some of them movies and some shows, but definitely incomplete in both respects.

I use the list in Kometa (Plex Meta Manager), but it too reports finding only 11 items from the list. What am I doing wrong?

**Comment by linaspurinis** [comment]
Hi, thank you. I found the bug in the code, could you please check now? It should display both movies and shows.

**Comment by Cheezzhead** [comment]
It works, thanks!

Though now my static lists are displayed as empty. Not entirely sure if this was already the case prior to your change but perhaps it's related?

**Comment by linaspurinis** [comment]
Yes, it was related. Should work now.

**Comment by Cheezzhead** [comment]
Awesome, thanks for everything!
