### ISSUE TITLE
More sources of reviews

### ISSUE THREAD

**Issue by linaspurinis** [linaspurinis/mdblist.com#6]
[Root-FTW](https://github.com/Root-FTW)
I found more sources of reviews that can help in MDBLIST.

on this site i noticed they get reviews from major sites.
It would be very VERY great if mdblist would also consider those reviews.

[This is the site/example:](https://torrent-track.app/title/tt10365998)

[API example 🙂](https://api.torrent-track.app/meta/tt10365998.json)

[analyzing the json I think it uses the metacritic API to get those reviews (but I'm not 100% sure)](https://jsonhero.io/j/9EDX2dYai2YP)

**Comment by linaspurinis** [comment]
I added Metacritic reviews directly because the source does not provide a rating. However, I will use the site for external ID rechecks. Example of refreshed movie: https://mdblist.com/movie/tt10365998

**Comment by linaspurinis** [comment]
test

**Comment by Root-FTW** [comment]
> I added Metacritic reviews directly because the source does not provide a rating. However, I will use the site for external ID rechecks. Example of refreshed movie: https://mdblist.com/movie/tt10365998

OMG it's incredible, it's perfect, thank you very much for being so attentive with this project that many of us love.

Is there a tentative date in which this review change/update will be reflected in all mdblist movies?

**Comment by linaspurinis** [comment]
Every item has its own schedule for a refresh, trying to force it for so many items can lead to an IP ban. It should take about 2-3 weeks for recent titles and more for older.
