### ISSUE TITLE
[FR] Custom Sorting

### ISSUE THREAD

**Issue by Drazzilb08** [linaspurinis/mdblist.com#9]
This wasn't an original idea by my self but saw that it didn't get any traction from Overlord on the Discord server.
https://discord.com/channels/907169977159786516/907171632265715723/956560728356192296

Essentially the ability to sort items with a custom sort. This would be helpful with such applications such as Plex-Meta-Manager and using their custom sorting to import certain universes in chronological or watching order. (think MCU) 

If there currently is a way to do this I did not clearly see it. Thank you

**Comment by linaspurinis** [comment]
Custom sorting has been added. You can now add a custom number for your list items and use this to sort your list.
